config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/show'
  get 'posts/new'
  get 'posts/edit'
  resources :users
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :posts
  has_many :ratings

  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :genre, presence: true
  # validates :category, inclusion: { in: ['chinese', 'italian', 'french', 'belgian', 'japanese'] }
end

  # <%= f.input :name %>
  # <%= f.input :genre %>
  # <%= f.input :image_url %>
  # <%= f.input :description %>
  # <%= f.input :price %>
  # <%= f.input :rating %>

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :game
  belongs_to :user
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :game
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  has_many :ratings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  def index
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.save
    redirect_to @game
  end

  def edit
  end

  def update
    @game.update(game_params)
    redirect_to @game
  end

  def show
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:name, :genre, :image_url, :description, :price, :rating)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to games_url
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password, :email, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.erb
<%= simple_form_for @game do |f| %>
  <%= f.input :name %>
  <%= f.input :genre %>
  <%= f.input :image_url %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :rating %>
  <%= f.submit "Add Game", class: "btn btn-success" %>
<% end %>

app/views/games/edit.html.erb
<h1>Games#edit</h1>
<p>Find me in app/views/games/edit.html.erb</p>
<%= render 'form', game: @game %>

app/views/games/index.html.erb
<h1>Games#index</h1>
<p>Find me in app/views/games/index.html.erb</p>
<% @games.each_with_index do |game, index| %>
  <% if index % 3 == 0 && index != 0 %>
    </div>
  <% end %>
  <% if index % 3 == 0 %>
    <div class="row">
  <% end %>
  <div class="col-xs-12 col-sm-4">
    <%= link_to game do %>
    <div class="game-card">
      <div class="game-card-image" style = "background-image: url(<%= game.image_url %>)">
        <div class='game-price'>
          <p><i class="fas fa-dollar-sign"></i><%= game.price %></p>
        </div>
      </div>
      <div class="game-card-content">
        <div class="game-info">
          <h2><%= game.name %></h2>
          <p><%= game.description %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
<% end %>

app/views/games/new.html.erb
<h1>Games#new</h1>
<p>Find me in app/views/games/new.html.erb</p>
<%= render 'form', game: @game %>

app/views/games/show.html.erb
<h1><%= @game.name %></h1>
<p>Find me in app/views/games/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsGames</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to "Gamesland", games_path, class: "navbar-brand" %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.input :email %>
  <%= f.input :description %>
  <%= f.submit "Sign In", class: "btn btn-success" %>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>